### ISSUE TITLE
Description of arguments

### ISSUE THREAD

**Issue by poohzrn** [mp2893/gram#1]
Hello Edward,
Can you give a description of the format of the [arguments](https://github.com/mp2893/gram/blob/master/gram.py#L372-L375):
```
if __name__ == '__main__':
	seqFile = sys.argv[1]
	treeFile = sys.argv[2]
	labelFile = sys.argv[3]
	outPath = sys.argv[4]
```

**Comment by mp2893** [comment]
Sorry for the delay.
I will write a proper README.
