### ISSUE TITLE
function arguments 

### ISSUE THREAD

**Issue by panford** [mp2893/gram#10]
I'm wondering why this code snippet `for index in random.sample(range(n_batches) , n_batches)` in the train_GRAM function in **gram.py** is passed two arguments - range(n_batches) and n_batches, instead of max. one from `np.random.sample` documentation. Its not working for me at least. Any comment will be highly appreciated.

**Comment by mp2893** [comment]
Maybe you are mistaking Python's random.sample function with numpy's random.sample function?

**Comment by panford** [comment]
Yes. That was right. I got it now. Thanks
