### ISSUE TITLE
Needing the code for calculating metrics

### ISSUE THREAD

**Issue by BarryRun** [mp2893/gram#14]
Could you please upload your code about calculating the metric "accuracy @ k" when getting y_hat and y?

I am not familiar with theano and I will appreciate you that if you can upload corresponding code, then I can do some comparative experiment based on your code.

Thanks a lot!

**Comment by mp2893** [comment]
Hi BarryRun,

Thanks for taking interest in my code.
Please note that calculating "Acc@k" does not require any knowledge on Theano.
You run the Theano part to obtain y_hat (which should be a Numpy object), then you can write a simple accuracy evaluation code purely in Python.

Best,
Ed
