### ISSUE TITLE
Loading embedding file from glove training

### ISSUE THREAD

**Issue by Angeela03** [mp2893/gram#17]
After running glove.py, how is the embedding file stored in the end?  What do we pass as an embedding file in gram.py?

**Comment by mp2893** [comment]
There is a step-by-step instruction as to how to execute the code. 
Specifically, please refer to Step 3.

**Comment by Angeela03** [comment]
In Step 3, it is not clear what to pass as the "embedding path" argument while training gram.py. I don't see an embedding file being stored in the previous step. We are only outputting the logs. Or maybe I am not understanding it properly.

**Comment by mp2893** [comment]
Doesn't glove.py accept <output path> as an argument? That should be where the trained embeddings are stored.
(I wrote this code 6 years ago, so I'm completely sure about the details anymore...)
